services:
  # Development service with hot reloading (default)
  weather-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
    restart: unless-stopped
    
  # Production service (use with --profile prod)
  weather-app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - prod
